namespace SharpVideo.H264;

/// <summary>
/// H.264 SEI (Supplemental Enhancement Information) payload types.
/// From Table D-1 of the H.264/AVC specification.
/// </summary>
public enum SeiPayloadType
{
    BufferingPeriod = 0,
    PicTiming = 1,
    PanScanRect = 2,
    FillerPayload = 3,
    UserDataRegisteredItuTT35 = 4,
    UserDataUnregistered = 5,
    RecoveryPoint = 6,
    DecRefPicMarkingRepetition = 7,
    SparePic = 8,
    SceneInfo = 9,
    SubSeqInfo = 10,
    SubSeqLayerCharacteristics = 11,
    SubSeqCharacteristics = 12,
    FullFrameFreeze = 13,
    FullFrameFreezeRelease = 14,
    FullFrameSnapshot = 15,
    ProgressiveRefinementSegmentStart = 16,
    ProgressiveRefinementSegmentEnd = 17,
    MotionConstrainedSliceGroupSet = 18,
    FilmGrainCharacteristics = 19,
    DeblockingFilterDisplayPreference = 20,
    StereoVideoInfo = 21,
    PostFilterHint = 22,
    ToneMappingInfo = 23,
    ScalabilityInfo = 24,
    SubPicScalableLayer = 25,
    NonRequiredLayerRep = 26,
    PriorityLayerInfo = 27,
    LayersNotPresent = 28,
    LayerDependencyChange = 29,
    ScalableNesting = 30,
    BaseLayerTemporalHrd = 31,
    QualityLayerIntegrityCheck = 32,
    RedundantPicProperty = 33,
    Tl0DepRepIndex = 34,
    TlSwitchingPoint = 35,
    ParallelDecodingInfo = 36,
    MvcScalableNesting = 37,
    ViewScalabilityInfo = 38,
    MultiviewSceneInfo = 39,
    MultiviewAcquisitionInfo = 40,
    NonRequiredViewComponent = 41,
    ViewDependencyChange = 42,
    OperationPointsNotPresent = 43,
    BaseViewTemporalHrd = 44,
    FramePackingArrangement = 45,
    MultiviewViewPosition = 46,
    DisplayOrientation = 47,
    MvcdScalableNesting = 48,
    MvcdViewScalabilityInfo = 49,
    DepthRepresentationInfo = 50,
    ThreeDimensionalReferenceDisplaysInfo = 51,
    DepthTiming = 52,
    DepthSamplingInfo = 53,
    ConstrainedDepthParameterSetIdentifier = 54,
    MasteringDisplayColourVolume = 137,
    ContentLightLevelInfo = 144,
    AlternativeTransferCharacteristics = 147
}
