<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <Title>SharpVideo</Title>
    <Description>Some management abstractions over V4L2, DRM, etc.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpVideo.Linux.Native\SharpVideo.Linux.Native.csproj" />
  </ItemGroup>

</Project>
